# Generated by Django 3.1.4 on 2022-04-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuisine_name', models.TextField()),
            ],
            options={
                'db_table': 'cuisine',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('home_address', models.TextField()),
                ('work_address', models.TextField()),
                ('mail_id', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('card_number', models.BigIntegerField(blank=True, null=True)),
                ('upi_id', models.TextField(blank=True, null=True)),
                ('home_pincode', models.IntegerField()),
                ('work_pincode', models.IntegerField()),
                ('membership_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dish_name', models.TextField()),
                ('category', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.cuisine')),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('veg', models.IntegerField(blank=True, null=True)),
                ('exotic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('outlet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'outlet',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('acc_no', models.BigIntegerField(blank=True, null=True)),
                ('ifsc_code', models.TextField()),
                ('role_assigned', models.TextField(blank=True, null=True)),
                ('base_salary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.staff')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.outlet')),
            ],
            options={
                'db_table': 'chef',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.staff')),
                ('outlet_id', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery_person',
            },
        ),
        migrations.CreateModel(
            name='DineTable',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('outlet_id', models.IntegerField()),
                ('category', models.TextField()),
                ('num_persons', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dine_table',
                'unique_together': {('table_id', 'outlet_id')},
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.staff')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.outlet')),
            ],
            options={
                'db_table': 'waiter',
            },
        ),
        migrations.CreateModel(
            name='OtherStaff',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.staff')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.outlet')),
            ],
            options={
                'db_table': 'other_staff',
            },
        ),
        migrations.CreateModel(
            name='OrderRelation',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('payment_mode', models.TextField(blank=True, null=True)),
                ('order_type', models.TextField(blank=True, null=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.outlet')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.deliveryperson')),
            ],
            options={
                'db_table': 'order_relation',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.staff')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.outlet')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='WaiterTable',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.staff')),
                ('outlet_id', models.IntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dinetable')),
            ],
            options={
                'db_table': 'waiter_table',
                'unique_together': {('staff', 'table')},
            },
        ),
        migrations.CreateModel(
            name='OutletIngredient',
            fields=[
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.outlet')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('quantity_unit', models.TextField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ingredients')),
            ],
            options={
                'db_table': 'outlet_ingredient',
                'unique_together': {('outlet', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.orderrelation')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.chef')),
            ],
            options={
                'db_table': 'order_dish',
                'unique_together': {('order', 'dish')},
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.dish')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('quantity_unit', models.TextField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ingredients')),
            ],
            options={
                'db_table': 'dish_ingredient',
                'unique_together': {('dish', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='CustomerOutlet',
            fields=[
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.outlet')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer')),
            ],
            options={
                'db_table': 'customer_outlet',
                'unique_together': {('outlet', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='ChefExpertise',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.chef')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.cuisine')),
            ],
            options={
                'db_table': 'chef_expertise',
                'unique_together': {('staff', 'cuisine')},
            },
        ),
    ]
